project:
  type: website

website:
  title: "Yann Say"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: apps.qmd
        text: Data applications - projects
      - href: packages.qmd
        text: R Packages
      - href: books.qmd
        text: Books and presentations
        
    right:
      - icon: github
        href: https://github.com/yannsay-impact
      - icon: github
        href: https://github.com/yannsay
      - icon: linkedin
        href: https://www.linkedin.com/in/yann-say-liang-fat-83476448/
format:
  html:
    theme: simplex
    css: styles.css

editor: visual

